# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  SwanEditor_config = debug
  Swan_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  SwanEditor_config = release
  Swan_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  SwanEditor_config = dist
  Swan_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad ImGui SwanEditor Swan

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Swan/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Swan/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Swan/vendor/ImGui -f Makefile config=$(ImGui_config)
endif

SwanEditor: Swan GLFW Glad ImGui
ifneq (,$(SwanEditor_config))
	@echo "==== Building SwanEditor ($(SwanEditor_config)) ===="
	@${MAKE} --no-print-directory -C SwanEditor -f Makefile config=$(SwanEditor_config)
endif

Swan: GLFW Glad ImGui
ifneq (,$(Swan_config))
	@echo "==== Building Swan ($(Swan_config)) ===="
	@${MAKE} --no-print-directory -C Swan -f Makefile config=$(Swan_config)
endif

clean:
	@${MAKE} --no-print-directory -C Swan/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Swan/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Swan/vendor/ImGui -f Makefile clean
	@${MAKE} --no-print-directory -C SwanEditor -f Makefile clean
	@${MAKE} --no-print-directory -C Swan -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   SwanEditor"
	@echo "   Swan"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"